ai001 find suitable dataset - done
Andrewwango/kainosRecruitmentApi-TeamA pull request #11
Opened 2022-09-29 15:26 UTC by Andrewwango

Found 3 appropriate datasets to train on and compare. Also set up AI project structure in `/ai/` folder. Acceptance Criteria: Find a suitable dataset (done); Split the data into training, test and validation (taking an unsupervised approach so all data is used for training, and test data is a separate handmade testing dataset (explained in `/ai/01_eda.ipynb`)).

2022-09-29 15:34 UTC, Andrewwango commented
Placeholder to ask for Liam's review

2022-09-29 15:51 UTC, nataskainos approved these changes
Great job! I have no comments.

2022-09-29 16:18 UTC, ldonnellykainoscom commented
Looks really good! Interested to see where this goes. I like the references to the papers too.

Did you mean to leave the readme file empty? Or accidentally didn't commit the text?
If it's just empty, best to delete it 👍 

Same again for the empty or nearly empty notebooks. Ideally you want to only be merging 'production code' into main but ofc these are notebooks so not used in production but same principle of of committing working tidy code applies.

Other than that it looks tidy.

2022-09-29 16:20 UTC, ldonnellykainoscom requested changes

2022-09-29 16:20 UTC, ldonnellykainoscom commented on ai/01_eda.ipynb
> +    "The \"corpus\" datasets are used to train word embedding models (i.e. unsupervised learning) to be able to get vectors representing words. The similarity of vectors the n represent semantic asso
Should it be "the n vectors"

2022-09-29 16:20 UTC, ldonnellykainoscom commented on ai/01_eda.ipynb
> +    "**TODO** include all words + inflections in datasets"
Did you mean to leave this here? Probably best to not have any TODOs merged into main. I guess you can leave the inflections to the pre-processing ticket

2022-09-29 17:10 UTC, Andrewwango commented on ai/01_eda.ipynb
> +    "**TODO** include all words + inflections in datasets"
Hi, fixed

2022-09-29 17:12 UTC, Andrewwango commented
> Looks really good! Interested to see where this goes. I like the references to the papers too.
> 
> Did you mean to leave the readme file empty? Or accidentally didn't commit the text? If it's just empty, best to delete it 👍
> 
> Same again for the empty or nearly empty notebooks. Ideally you want to only be merging 'production code' into main but ofc these are notebooks so not used in production but same principle of of committing working tidy code applies.
> 
> Other than that it looks tidy.

Cheers Liam, I didn't realise that was best practice, I've removed all non-essential notebooks to this ticket. And yeah README was just a placeholder before.

2022-09-30 07:32 UTC, hellofadude approved these changes
Approved!

2022-09-30 07:39 UTC, merged