Ai002 eda ticket done
Andrewwango/kainosRecruitmentApi-TeamA pull request #13
Opened 2022-09-30 11:33 UTC by Andrewwango

Update to EDA notebook showing datasets for training and testing.

As AI Engineer I want to have a better understanding of the data so I know how it can be used to create a model

Acceptance Criteria:

- _Import the train data into a Jupyter notebook locally_ (see `01_EDA.ipynb` descriptions of training and testing datasets, of which there are several)
- _Get insights from the text itself_ (see notebook for examples of the unstructured text datasets)
- _Look into distributions of the columns. Looks for class imbalance. Make use of graphs to shows key insights from the data._ (we are now approaching the task as unsupervised so there are no training classes. Instead we look at a wordcloud of the data, size, average sentence length etc. For testing dataset we have curated labels, so we can look at class sizes).

2022-10-03 13:21 UTC, KewinTaoAnh approved these changes

2022-10-05 15:48 UTC, ldonnellykainoscom commented
Hey, I probably should have suggested these changes in the last pr but I had to use the following to get the wikipedia dataset so maybe include:

! cat ./data/rlebret-wikipedia-biography-dataset-d0d6c78/wikipedia-biography-dataset.z?? > ./data/tmp.zip
! unzip ./data/tmp.zip -d ./data
! rm ./data/tmp.zip

You could add a markdown cell above e.g:
'Unzip the folder manually through the file explorer and place in /data folder'


Might be overkill but for the Doughman dataset you could use the link directly (very nit picky):
dataset = pd.read_csv("https://raw.githubusercontent.com/jaddoughman/Gender-Bias-Datasets-Lexicons/main/generic_pronouns/dataset.csv")

Still good to have the link there in markdown but anything to make it easy for someone in the future running this notebook and just wanting to click run on all the cells.

2022-10-05 15:52 UTC, ldonnellykainoscom commented
Btw (small point) I think most people use CSVs so you might might find it easier that way plus it's good to follow convention. Looks a little counter intuitive using df.to_csv('___.txt).

2022-10-05 15:57 UTC, ldonnellykainoscom commented
I like the use of tqdm btw!

2022-10-05 15:58 UTC, ldonnellykainoscom requested changes
Few small changes mostly for the sake of it ;)

2022-10-05 15:58 UTC, ldonnellykainoscom commented on ai/00_prep_datasets.ipynb
>      "!cat *.sent > dataset_wikibios.txt"
Had to modify this to get it to work for me:
! cat ./data/wikipedia-biography-dataset/*/*.sent > data/corpus/dataset_wikibios.txt
Also put the output file in the corpus folder as that's where it's referenced from in the eda notebook later

2022-10-05 15:58 UTC, ldonnellykainoscom commented on ai/00_prep_datasets.ipynb
> +    "with open(\"nb_wikibios.txt\", \"r\") as f:\n",
Think you should get it from `./data/corpus/`

2022-10-05 15:58 UTC, ldonnellykainoscom commented on ai/00_prep_datasets.ipynb
> +    "with open(\"dataset_wikibios.txt\", \"r\") as f:\n",
Think you should get it from `./data/corpus/`

2022-10-05 15:58 UTC, ldonnellykainoscom commented on ai/00_prep_datasets.ipynb
> +    "with open('dataset_wikibios_merged.txt', 'w') as f:\n",
Think you should get it from `./data/corpus/`

2022-10-05 15:58 UTC, ldonnellykainoscom commented on ai/00_prep_datasets.ipynb
> +    "from tqdm import tqdm\n",
Small point again - try keep you imports at the top (it's a bit of a loose convention). Other than that, the notebooks look really neat!

2022-10-05 15:58 UTC, ldonnellykainoscom commented on ai/01_eda.ipynb
> +    "print(average_sentence_length(dataset_BUG_stereotype))"
Might be a good opportunity for a histogram showing the distribution of sentence lengths.

2022-10-05 15:58 UTC, ldonnellykainoscom commented on ai/01_eda.ipynb
> +    "wordcloud = WordCloud().generate(\" \".join(dataset_wikibios_merged))\n",
Think this needs adding to the requirements.txt

2022-10-06 08:08 UTC, Andrewwango commented on ai/01_eda.ipynb
> +    "def average_sentence_length(dataset):\n",
Cheers, I think I'll leave this in here as it's just helper functions for EDA only used in this notebook rather than code for the API

2022-10-06 08:29 UTC, Andrewwango commented
> I like the use of tqdm btw!

I can't imagine life before tqdm...

2022-10-06 08:32 UTC, Andrewwango commented
> Btw (small point) I think most people use CSVs so you might might find it easier that way plus it's good to follow convention. Looks a little counter intuitive using df.to_csv('___.txt).

Yeah, it's a bit cheeky but a quick way to write a dataframe to a newline separated text file without the faff of open()

2022-10-06 17:17 UTC, ldonnellykainoscom commented
Nice! Ready to merge

2022-10-07 08:44 UTC, KainosDanny approved these changes

2022-10-07 08:49 UTC, hellofadude approved these changes

2022-10-07 09:01 UTC, merged