Ai004 explore models train - done
Andrewwango/kainosRecruitmentApi-TeamA pull request #23
Opened 2022-10-04 12:46 UTC by Andrewwango

As an AI Engineer I want to use multiple models to give a more accurate baseline performance before further experimenting 

AC as follows are for expected approach using supervised learning. However I have taken another approach (discussed with Liam) using unsupervised learning therefore the following AC are not relevant. 

- Use the SKLearn diagram to find a suitable model 
- Also include a gradient boosted model 
- Use test split to output the accuracy for each model 

The following is my approach on exploring models and training. Using the word embedding models from ai003 branch, I have developed a function to score whether input words are more biased towards male or female words, or are neutral, based on vector space learnt using word embedding model. These functions are included in `ai/api/` folder and demonstrated in `ai/02_train_model.ipynb`.

2022-10-07 08:35 UTC, ldonnellykainoscom requested changes

2022-10-11 12:41 UTC, marcoatkainos commented
Reviewed it with Andrew and it's good to go from my side!

2022-10-11 12:42 UTC, marcoatkainos approved these changes
Reviewed it with Andrew and it's good to go from my side!

2022-10-11 12:55 UTC, KainosDanny approved these changes

2022-10-11 13:14 UTC, hellofadude approved these changes

2022-10-11 13:19 UTC, merged