015 edit a role
Andrewwango/kainosRecruitmentApi-TeamA pull request #31
Opened 2022-10-12 10:02 UTC by JennicaMistry

2022-10-12 13:58 UTC, hellofadude commented on src/main/java/com/kainos/ea/dao/RoleFeaturesLevel.java
> +//                    "(\"" + jobRole.getRoleName() + "\",\"" + jobRole.getSpecification() + "\",\"" + jobRole.getBandID() + "\",\"" + jobRole.getCapabilityID() + "\",\"" + jobRole.getResponsibility(
Remove commented out code

2022-10-12 13:59 UTC, hellofadude commented on src/test/java/com/kainos/ea/dao/RoleFeatureLevelTest.java
> +
remove extra lines and end of file

2022-10-12 14:00 UTC, hellofadude commented on src/test/java/com/kainos/ea/integration/RoleFeatureIntegrationTest.java
> +
remove extra line

2022-10-12 14:01 UTC, hellofadude commented on src/test/java/com/kainos/ea/integration/RoleFeatureIntegrationTest.java
> +
Remove extra lines here and lines 75-76

2022-10-12 14:02 UTC, hellofadude commented on src/main/java/com/kainos/ea/dao/RoleFeaturesLevel.java
> +
remove extra lines and make consistent with rest of code

2022-10-12 14:03 UTC, hellofadude requested changes
Minor comments

2022-10-12 14:44 UTC, hellofadude commented on src/main/java/com/kainos/ea/dao/RoleFeaturesLevel.java
> +            System.out.println(jobRole.getBandID());
do you need these `System.out.println` statements? I think you can remove them

2022-10-12 14:44 UTC, hellofadude commented on src/main/java/com/kainos/ea/dao/RoleFeaturesLevel.java
> +            System.out.println(statement);
Here as well

2022-10-12 14:47 UTC, hellofadude commented on src/test/java/com/kainos/ea/dao/RoleFeatureLevelTest.java
> +    }
Add extra line here to signify start of new method

2022-10-13 09:58 UTC, hellofadude approved these changes

2022-10-13 10:08 UTC, marcoatkainos approved these changes

2022-10-13 10:42 UTC, Kahrym approved these changes

2022-10-13 10:42 UTC, merged